version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./carbon_tracker.db
      - ALLOWED_ORIGINS=http://localhost:3000
    volumes:
      - ./backend:/app
    networks:
      - carbon-tracker

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - carbon-tracker

  # Optional: PostgreSQL database
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: carbon_tracker_db
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - carbon-tracker

networks:
  carbon-tracker:
    driver: bridge

# volumes:
#   postgres_data: